Repository web-infra-dev/rstest, pull requests merged in 2025-06, with the labels that each got.

#247 fix: should print unhandled error correctly
  packages/core/src/cli/commands.ts
  packages/core/src/core/index.ts
  packages/core/src/pool/index.ts
  packages/core/src/reporter/index.ts
  packages/core/src/types/core.ts
  packages/core/src/types/reporter.ts
  tests/cli/fixtures/error.config.ts
  tests/cli/index.test.ts
Labels: change: fix

#251 docs: update URLs to use the new domain
  README.md
  packages/core/README.md
  website/README.md
  website/docs/en/guide/start/index.mdx
  website/docs/zh/guide/start/index.mdx
  website/rspress.config.ts
  website/theme/components/Hero.tsx
  website/theme/components/RsbuildDocBadge.tsx
Labels: change: docs

#254 feat: init testEnvironment configuration
  packages/core/src/cli/commands.ts
  packages/core/src/config.ts
  packages/core/src/pool/index.ts
  packages/core/src/types/config.ts
  packages/core/src/types/worker.ts
Labels: change: feat

#257 docs: add Samply profiling guide
  scripts/dictionary.txt
  website/docs/en/guide/advanced/profiling.mdx
  website/docs/zh/guide/advanced/profiling.mdx
Labels: change: docs

#259 fix: only print failed files when test error
  packages/core/src/core/listTests.ts
Labels: change: fix

#270 release: 0.0.1
  packages/core/package.json
Labels: release

#284 feat: support `jsdom` test
  examples/react/package.json
  examples/react/rsbuild.config.ts
  examples/react/rstest.config.ts
  examples/react/src/App.css
  examples/react/src/App.tsx
  examples/react/src/env.d.ts
  examples/react/src/index.tsx
  examples/react/test/App.test.tsx
  examples/react/tsconfig.json
  packages/core/package.json
  packages/core/src/runtime/worker/env/jsdom.ts
  packages/core/src/runtime/worker/env/jsdomKeys.ts
  packages/core/src/runtime/worker/index.ts
  packages/core/src/types/config.ts
  packages/core/src/types/environment.ts
  packages/core/src/types/index.ts
  pnpm-lock.yaml
  tests/jsdom/fixtures/package.json
  tests/jsdom/fixtures/rsbuild.config.ts
  tests/jsdom/fixtures/rstest.config.ts
  tests/jsdom/fixtures/src/App.css
  tests/jsdom/fixtures/src/App.tsx
  tests/jsdom/fixtures/src/env.d.ts
  tests/jsdom/fixtures/src/index.tsx
  tests/jsdom/fixtures/test/App.test.tsx
  tests/jsdom/fixtures/test/handledError.test.tsx
  tests/jsdom/fixtures/test/unhandledError.test.tsx
  tests/jsdom/fixtures/tsconfig.json
  tests/jsdom/handledError.test.ts
  tests/jsdom/index.test.ts
  tests/jsdom/unhandledError.test.ts
Labels: change: feat

#286 docs: add `include` and `exclude` configs
  packages/core/src/config.ts
  website/docs/en/config/_meta.json
  website/docs/en/config/index.mdx
  website/docs/en/config/test/_meta.json
  website/docs/en/config/test/exclude.mdx
  website/docs/en/config/test/include.mdx
  website/docs/zh/config/_meta.json
  website/docs/zh/config/index.mdx
  website/docs/zh/config/test/_meta.json
  website/docs/zh/config/test/exclude.mdx
  website/docs/zh/config/test/include.mdx
Labels: change: docs

#285 feat: support mock timers
  packages/core/LICENSE
  packages/core/package.json
  packages/core/rslib.config.ts
  packages/core/src/runtime/api/fakeTimers.ts
  packages/core/src/runtime/api/poll.ts
  packages/core/src/runtime/api/utilities.ts
  packages/core/src/runtime/runner/runner.ts
  packages/core/src/runtime/runner/task.ts
  packages/core/src/runtime/worker/console.ts
  packages/core/src/types/mock.ts
  pnpm-lock.yaml
  tests/fakeTimers/index.test.ts
Labels: change: feat

#295 fix: should interopDefault in node test environment by default
  packages/core/src/runtime/worker/index.ts
  tests/externals/interop.test.ts
Labels: change: fix

#301 release: 0.0.2
  packages/core/package.json
Labels: release

#304 docs: add `includeSource` configuration
  website/docs/en/config/test/_meta.json
  website/docs/en/config/test/includeSource.mdx
  website/docs/en/guide/start/quick-start.mdx
  website/docs/zh/config/test/_meta.json
  website/docs/zh/config/test/includeSource.mdx
  website/docs/zh/guide/start/quick-start.mdx
Labels: change: docs

#305 docs: add `setupFiles` configuration
  website/docs/en/config/test/_meta.json
  website/docs/en/config/test/setupFiles.mdx
  website/docs/zh/config/test/_meta.json
  website/docs/zh/config/test/setupFiles.mdx
Labels: change: docs

#312 docs: add `testEnvironment` configuration
  scripts/dictionary.txt
  website/docs/en/config/test/_meta.json
  website/docs/en/config/test/testEnvironment.mdx
  website/docs/zh/config/test/_meta.json
  website/docs/zh/config/test/testEnvironment.mdx
Labels: change: docs

#323 docs: add `plugins` configuration
  website/docs/en/api/rstest/_meta.json
  website/docs/en/config/_meta.json
  website/docs/en/config/build/plugins.mdx
  website/docs/zh/api/rstest/_meta.json
  website/docs/zh/config/_meta.json
  website/docs/zh/config/build/plugins.mdx
Labels: change: docs

#324 feat: support `externals` configuration
  packages/core/src/core/rsbuild.ts
  packages/core/src/types/config.ts
  packages/core/tests/core/__snapshots__/rsbuild.test.ts.snap
  tests/jsdom/fixtures/rstest.externals.config.ts
  tests/jsdom/index.test.ts
  website/docs/en/config/build/output.mdx
  website/docs/zh/config/build/output.mdx
Labels: change: feat

#325 docs: add source configurations
  website/docs/en/config/build/_meta.json
  website/docs/en/config/build/source.mdx
  website/docs/zh/config/build/_meta.json
  website/docs/zh/config/build/source.mdx
Labels: change: docs

#326 fix: node built-in modules should follow external strategy
  packages/core/src/core/rsbuild.ts
  packages/core/src/utils/helper.ts
  packages/core/tests/core/__snapshots__/rsbuild.test.ts.snap
  packages/core/tests/core/rsbuild.test.ts
Labels: change: fix

#327 feat: handle process.exit in pool
  packages/core/src/runtime/worker/index.ts
  tests/runner/test/processExit.test.ts
Labels: change: feat

#329 docs: add more build configs
  website/docs/en/config/build/_meta.json
  website/docs/en/config/build/dev.mdx
  website/docs/en/config/build/performance.mdx
  website/docs/en/config/build/resolve.mdx
  website/docs/en/config/build/tools.mdx
  website/docs/zh/config/build/_meta.json
  website/docs/zh/config/build/dev.mdx
  website/docs/zh/config/build/performance.mdx
  website/docs/zh/config/build/resolve.mdx
  website/docs/zh/config/build/tools.mdx
Labels: change: docs

#331 fix: interop lodash correctly
  packages/core/src/core/rsbuild.ts
  packages/core/src/runtime/worker/loadModule.ts
  packages/core/tests/core/__snapshots__/rsbuild.test.ts.snap
  pnpm-lock.yaml
  tests/externals/fixtures/interopDefault.test.ts
  tests/externals/fixtures/interopLodash.test.ts
  tests/externals/fixtures/test-lodash/index.js
  tests/externals/fixtures/test-lodash/package.json
  tests/externals/fixtures/test-pkg/importLodash.ts
  tests/externals/fixtures/test-pkg/interopDefault.ts
  tests/externals/interop.test.ts
Labels: change: fix

#333 fix(spy): fix mockImplementation for function overload and unions
  packages/core/src/runtime/api/spy.ts
  packages/core/src/types/mock.ts
  tests/spy/index.test.ts
Labels: change: fix

#335 docs: add test API
  packages/core/src/runtime/api/snapshot.ts
  website/docs/en/api/_meta.json
  website/docs/en/api/test-api/test.mdx
  website/docs/zh/api/_meta.json
  website/docs/zh/api/test-api/test.mdx
Labels: change: docs
