Repository web-infra-dev/rstest, pull requests merged in 2025-04, with the labels that each got.

#68 feat: integrate snapshot API
  README.md
  packages/core/package.json
  packages/core/src/api/expect.ts
  packages/core/src/api/index.ts
  packages/core/src/api/poll.ts
  packages/core/src/api/public.ts
  packages/core/src/api/snapshot.ts
  packages/core/src/core/context.ts
  packages/core/src/pool/index.ts
  packages/core/src/runner/index.ts
  packages/core/src/runner/runner.ts
  packages/core/src/runner/runtime.ts
  packages/core/src/types/core.ts
  packages/core/src/types/global.ts
  packages/core/src/types/testSuite.ts
  packages/core/src/types/worker.ts
  packages/core/src/worker/index.ts
  pnpm-lock.yaml
  tests/snapshot/__snapshots__/index.test.ts.snap
  tests/snapshot/index.test.ts
Labels: change: feat

#67 feat: support afterAll
  packages/core/src/api/public.ts
  packages/core/src/index.ts
  packages/core/src/runner/index.ts
  packages/core/src/runner/runner.ts
  packages/core/src/runner/runtime.ts
  packages/core/src/types/api.ts
  packages/core/src/types/testSuite.ts
  pnpm-lock.yaml
  scripts/dictionary.txt
  tests/afterAll/fixtures/index.test.ts
  tests/afterAll/index.test.ts
  tests/afterAll/package.json
  tests/afterAll/rstest.config.ts
  tests/package.json
  tests/rstest.config.ts
  tests/scripts/index.ts
Labels: change: feat

#69 feat: support update snapshot via `update` configuration
  packages/core/src/cli/commands.ts
  packages/core/src/config.ts
  packages/core/src/core/context.ts
  packages/core/src/types/config.ts
Labels: change: feat

#70 feat: support print snapshot summary log
  packages/core/src/core/runTests.ts
  packages/core/src/pool/index.ts
  packages/core/src/reporter/index.ts
  packages/core/src/reporter/summary.ts
  packages/core/src/runner/runner.ts
  packages/core/src/types/reporter.ts
  packages/core/src/types/testSuite.ts
  packages/core/src/utils/helper.ts
Labels: change: feat

#74 feat: support `reporters` in config
  packages/core/package.json
  packages/core/rslib.config.ts
  packages/core/src/config.ts
  packages/core/src/core/context.ts
  packages/core/src/index.ts
  packages/core/src/node.ts
  packages/core/src/types/config.ts
  packages/core/src/types/reporter.ts
  packages/core/src/worker/loadModule.ts
  pnpm-lock.yaml
  tests/afterAll/index.test.ts
  tests/package.json
  tests/reporter/fixtures/index.test.ts
  tests/reporter/index.test.ts
  tests/reporter/package.json
  tests/reporter/rstest.config.ts
  tests/reporter/rstest.customReporterConfig.ts
  tests/reporter/rstest.emptyReporterConfig.ts
  tests/scripts/index.ts
Labels: change: feat

#78 fix: should get current test from runner
  packages/core/src/reporter/summary.ts
  packages/core/src/runner/index.ts
  packages/core/src/runner/runner.ts
  packages/core/src/runner/runtime.ts
  pnpm-lock.yaml
  tests/package.json
  tests/snapshot/__snapshots__/index.test.ts.snap
  tests/snapshot/file.test.ts
  tests/snapshot/fixtures/index.test.ts
  tests/snapshot/index.test.ts
Labels: change: fix

#80 feat: support summary & print setup error
  packages/core/package.json
  packages/core/src/cli/commands.ts
  packages/core/src/config.ts
  packages/core/src/core/rsbuild.ts
  packages/core/src/pool/forks.ts
  packages/core/src/reporter/index.ts
  packages/core/src/reporter/summary.ts
  packages/core/src/runner/runner.ts
  packages/core/src/types/testSuite.ts
  packages/core/src/utils/helper.ts
  packages/core/src/utils/runtime.ts
  packages/core/src/utils/testFiles.ts
  packages/core/src/worker/index.ts
  packages/core/src/worker/loadModule.ts
  pnpm-lock.yaml
  tests/rstest.setup.ts
  tests/setup/fixtures/basic/index.test.ts
  tests/setup/fixtures/basic/rstest.config.ts
  tests/setup/fixtures/basic/rstest.setup.ts
  tests/setup/fixtures/error/index.test.ts
  tests/setup/fixtures/error/rstest.config.ts
  tests/setup/fixtures/error/rstest.setup.ts
  tests/setup/index.test.ts
Labels: change: feat

#63 feat: support basic watch mode
  .gitignore
  examples/node/package.json
  packages/core/src/cli/commands.ts
  packages/core/src/core/rsbuild.ts
  packages/core/src/core/runTests.ts
  packages/core/src/env.d.ts
  pnpm-lock.yaml
  tests/afterAll/index.test.ts
  tests/cli/index.test.ts
  tests/reporter/index.test.ts
  tests/rstest.config.ts
  tests/scripts/index.ts
  tests/scripts/utils.ts
  tests/setup/index.test.ts
  tests/snapshot/file.test.ts
  tests/watch/fixtures/index.test.ts
  tests/watch/fixtures/src/index.ts
  tests/watch/index.test.ts
  tests/watch/package.json
  tests/watch/rstest.config.ts
Labels: change: feat

#82 feat: support register async suite
  packages/core/src/runner/index.ts
  packages/core/src/runner/runtime.ts
  packages/core/tests/runner/runtime.test.ts
  tests/isolate/test/index.test.ts
  tests/isolate/test/index1.test.ts
  tests/runner/test/async.test.ts
  tests/runner/test/fixtures/async.test.ts
  tests/scripts/utils.ts
Labels: change: feat

#83 fix: get build time from Rspack stats
  packages/core/src/core/rsbuild.ts
  packages/core/src/core/runTests.ts
Labels: change: fix

#87 feat: support beforeAll
  packages/core/src/api/public.ts
  packages/core/src/runner/index.ts
  packages/core/src/runner/runner.ts
  packages/core/src/runner/runtime.ts
  packages/core/src/types/api.ts
  packages/core/src/types/testSuite.ts
  pnpm-lock.yaml
  tests/lifecycle/fixtures/afterAll.test.ts
  tests/lifecycle/fixtures/beforeAll.test.ts
  tests/lifecycle/index.test.ts
  tests/lifecycle/package.json
  tests/lifecycle/rstest.config.ts
Labels: change: feat

#88 feat: support print diff
  packages/core/package.json
  packages/core/src/pool/index.ts
  packages/core/src/reporter/summary.ts
  packages/core/src/types/testSuite.ts
  packages/core/src/utils/runtime.ts
  pnpm-lock.yaml
  tests/diff/fixtures/index.test.ts
  tests/diff/index.test.ts
Labels: change: feat

#92 fix: should not run hooks when no test case execution
  packages/core/src/runner/runner.ts
  packages/core/src/runner/runtime.ts
  packages/core/src/types/testSuite.ts
  packages/core/tests/runner/runner.test.ts
  tests/lifecycle/fixtures/skip.test.ts
  tests/lifecycle/index.test.ts
Labels: change: fix

#95 fix: should mark test fail when no test in suite
  packages/core/src/runner/runner.ts
  tests/noTests/fixtures/noTestInSuite.test.ts
  tests/noTests/fixtures/noTests.test.ts
  tests/noTests/index.test.ts
  tests/rstest.config.ts
Labels: change: fix

#100 feat: support handle hooks error
  packages/core/src/reporter/summary.ts
  packages/core/src/runtime/runner/runner.ts
  packages/core/src/runtime/util.ts
  tests/lifecycle/error.test.ts
  tests/lifecycle/fixtures/error/afterAll.test.ts
  tests/lifecycle/fixtures/error/afterEach.test.ts
  tests/lifecycle/fixtures/error/beforeAll.test.ts
  tests/lifecycle/fixtures/error/beforeAllRoot.test.ts
  tests/lifecycle/fixtures/error/beforeEach.test.ts
  tests/lifecycle/index.test.ts
Labels: change: feat

#101 feat: support hooks timeout
  packages/core/src/runtime/runner/runtime.ts
  packages/core/src/types/api.ts
  tests/lifecycle/fixtures/timeout.test.ts
  tests/lifecycle/timeout.test.ts
Labels: change: feat

#103 feat: support describe skip & todo
  packages/core/src/runtime/runner/index.ts
  packages/core/src/runtime/runner/runner.ts
  packages/core/src/runtime/runner/runtime.ts
  packages/core/src/types/api.ts
  packages/core/src/types/testSuite.ts
  tests/describe/fixtures/skip.test.ts
  tests/describe/fixtures/todo.test.ts
  tests/describe/index.test.ts
Labels: change: feat

#105 feat: allow test function undefined
  packages/core/src/runtime/runner/index.ts
  packages/core/src/runtime/runner/runner.ts
  packages/core/src/runtime/runner/runtime.ts
  packages/core/src/types/api.ts
  packages/core/src/types/testSuite.ts
  tests/expect/test/fixtures/undefined.test.ts
  tests/expect/test/index.test.ts
Labels: change: feat

#108 feat: support filter by testNamePattern
  packages/core/src/cli/commands.ts
  packages/core/src/runtime/runner/runner.ts
  packages/core/src/runtime/runner/task.ts
  packages/core/src/types/config.ts
  packages/core/src/types/testSuite.ts
  packages/core/src/utils/helper.ts
  packages/core/tests/runner/runner.test.ts
  tests/filter/fixtures/testNamePattern.test.ts
  tests/filter/testNamePattern.test.ts
Labels: change: feat

#109 feat: support testNamePattern RegExp
  packages/core/src/pool/index.ts
  packages/core/src/runtime/worker/index.ts
  packages/core/src/utils/helper.ts
  tests/filter/fixtures/testNamePattern.config.ts
  tests/filter/testNamePattern.test.ts
Labels: change: feat

#114 feat: add test timeout
  packages/core/src/runtime/runner/index.ts
  packages/core/src/runtime/runner/runtime.ts
  packages/core/src/types/api.ts
  packages/core/src/types/testSuite.ts
  tests/expect/test/fixtures/timeout.test.ts
  tests/expect/test/index.test.ts
Labels: change: feat

#115 feat: support `testTimeout` configuration
  packages/core/src/cli/commands.ts
  packages/core/src/config.ts
  packages/core/src/runtime/runner/index.ts
  packages/core/src/runtime/runner/runtime.ts
  packages/core/src/types/config.ts
  tests/expect/test/index.test.ts
Labels: change: feat

#117 feat: support get test file path via `beforeAll` context
  packages/core/src/runtime/runner/runner.ts
  packages/core/src/types/testSuite.ts
  tests/lifecycle/fixtures/beforeAll.test.ts
  tests/setup/fixtures/basic/rstest.setup.ts
Labels: change: feat

#118 fix: unexpected rpc error about result.expected
  packages/core/src/runtime/util.ts
  tests/expect/test/edgeCase.test.ts
  tests/expect/test/fixtures/error.test.ts
Labels: change: fix

#119 fix: `module not found` errors should be silent at build
  packages/core/src/core/plugins/ignoreResolveError.ts
  packages/core/src/core/rsbuild.ts
  tests/expect/test/edgeCase.test.ts
  tests/expect/test/fixtures/moduleNotFound.test.ts
Labels: change: fix

#124 feat: init `rstest.fn`
  packages/core/package.json
  packages/core/src/runtime/api/index.ts
  packages/core/src/runtime/api/public.ts
  packages/core/src/runtime/api/spy.ts
  packages/core/src/runtime/api/utilities.ts
  packages/core/src/types/api.ts
  packages/core/src/types/index.ts
  packages/core/src/types/mock.ts
  packages/core/src/types/utils.ts
  pnpm-lock.yaml
  tests/spy/index.test.ts
Labels: change: feat

#125 feat: support `mockImplementation`
  packages/core/src/runtime/api/spy.ts
  packages/core/src/types/mock.ts
  tests/spy/index.test.ts
Labels: change: feat

#126 fix: update global api
  packages/core/globals.d.ts
  packages/core/src/utils/constants.ts
  pnpm-lock.yaml
  tests/globals/fixtures/index.test.ts
  tests/globals/fixtures/package.json
  tests/globals/fixtures/tsconfig.json
  tests/globals/index.test.ts
Labels: change: fix

#128 feat: support mock `withImplementation`
  packages/core/src/runtime/api/spy.ts
  packages/core/src/types/mock.ts
  tests/spy/fixtures/withImplementation.test.ts
  tests/spy/withImplementation.test.ts
Labels: change: feat

#129 feat: support mock returns
  packages/core/src/runtime/api/spy.ts
  packages/core/src/types/mock.ts
  tests/spy/index.test.ts
Labels: change: feat

#130 feat: support read mock context
  packages/core/src/runtime/api/spy.ts
  packages/core/src/runtime/util.ts
  packages/core/src/types/mock.ts
  tests/diff/index.test.ts
  tests/spy/index.test.ts
  tests/spy/invocationCallOrder.test.ts
Labels: change: feat

#132 feat: support `rstest.spyOn`
  packages/core/src/runtime/api/spy.ts
  packages/core/src/runtime/api/utilities.ts
  packages/core/src/types/mock.ts
  tests/spy/spyOn.test.ts
Labels: change: feat

#135 fix: `expect.soft` api
  packages/core/src/runtime/runner/runner.ts
  packages/core/src/types/testSuite.ts
  tests/expect/test/fixtures/soft.test.ts
  tests/expect/test/index.test.ts
  tests/expect/test/soft.test.ts
  tests/setup/fixtures/basic/index.test.ts
  tests/setup/fixtures/basic/rstest.setup.ts
  tests/spy/index.test.ts
Labels: change: fix

#136 feat: support clearAllMocks / resetAllMocks / restoreAllMocks
  packages/core/src/runtime/api/spy.ts
  packages/core/src/runtime/api/utilities.ts
  packages/core/src/types/mock.ts
  tests/spy/clearAllMocks.test.ts
Labels: change: feat

#137 feat: support `rstest.isMockFunction`
  packages/core/src/runtime/api/spy.ts
  packages/core/src/runtime/api/utilities.ts
  packages/core/src/types/mock.ts
  tests/spy/index.test.ts
  tests/spy/spyOn.test.ts
Labels: change: feat

#138 docs(mock): add jsDoc for `mockInstance`
  packages/core/src/types/mock.ts
Labels: change: docs

#140 fix: should throw error when use `toMatchInlineSnapshot` in `test.each`
  packages/core/src/runtime/api/snapshot.ts
  packages/core/src/runtime/runner/runtime.ts
  packages/core/src/types/testSuite.ts
  tests/snapshot/fixtures/inlineSnapshot.each.test.ts
  tests/snapshot/index.test.ts
Labels: change: fix

#143 fix: update node engine range to >=18.0
  packages/core/package.json
Labels: change: fix

#144 feat: support array type cases in test `each` API
  packages/core/src/runtime/runner/index.ts
  packages/core/src/runtime/runner/runtime.ts
  packages/core/src/runtime/util.ts
  packages/core/src/types/api.ts
  tests/describe/each.test.ts
  tests/describe/fixtures/each.test.ts
  tests/runner/test/async.test.ts
  tests/scripts/utils.ts
  tests/test-api/each.test.ts
  tests/test-api/fixtures/each.test.ts
Labels: change: feat

#145 feat: support object type params in name template
  packages/core/src/runtime/runner/runtime.ts
  packages/core/src/runtime/util.ts
  packages/core/tests/runner/runtime.test.ts
  packages/core/tests/runner/util.test.ts
  tests/test-api/each.test.ts
Labels: change: feat

#146 fix: support printf-like string when format with object param
  packages/core/src/runtime/util.ts
  packages/core/tests/runner/util.test.ts
Labels: change: fix

#147 feat: support `stubEnv` & `unstubAllEnvs` API
  packages/core/src/runtime/api/index.ts
  packages/core/src/runtime/api/utilities.ts
  packages/core/src/types/mock.ts
  tests/spy/stubEnv.test.ts
Labels: change: feat

#149 feat: support `clearMocks` / `resetMocks` / `restoreMocks` configs
  packages/core/src/cli/commands.ts
  packages/core/src/config.ts
  packages/core/src/runtime/api/index.ts
  packages/core/src/runtime/runner/index.ts
  packages/core/src/runtime/runner/runner.ts
  packages/core/src/runtime/worker/index.ts
  packages/core/src/types/config.ts
  tests/spy/config.test.ts
  tests/spy/fixtures/clearMocks.test.ts
  tests/spy/fixtures/restoreMocks.test.ts
  tests/spy/withImplementation.test.ts
Labels: change: feat

#150 feat: support `stubGlobal` & `unstubAllGlobals` API
  packages/core/src/runtime/api/utilities.ts
  packages/core/src/types/mock.ts
  scripts/dictionary.txt
  tests/spy/stubGlobal.test.ts
Labels: change: feat

#151 feat: support `unstubEnvs` & `unstubGlobals` configs
  packages/core/src/cli/commands.ts
  packages/core/src/config.ts
  packages/core/src/runtime/runner/runner.ts
  packages/core/src/types/config.ts
Labels: change: feat

#155 feat: support retry failed test
  packages/core/src/cli/commands.ts
  packages/core/src/config.ts
  packages/core/src/runtime/runner/runner.ts
  packages/core/src/types/config.ts
  tests/test-api/fixtures/retry.test.ts
  tests/test-api/retry.test.ts
Labels: change: feat

#156 feat: support chain test api
  packages/core/src/runtime/runner/index.ts
  packages/core/src/runtime/runner/runtime.ts
  packages/core/src/types/api.ts
  tests/test-api/chain.test.ts
  tests/test-api/edgeCase.test.ts
  tests/test-api/fixtures/only.each.test.ts
  tests/test-api/fixtures/only.fails.test.ts
  tests/test-api/fixtures/onlyInSkip.test.ts
Labels: change: feat

#157 feat: support chain describe API
  packages/core/src/runtime/runner/index.ts
  packages/core/src/runtime/runner/runtime.ts
  packages/core/src/types/api.ts
  tests/describe/chain.test.ts
  tests/describe/fixtures/only.each.test.ts
  tests/describe/fixtures/skip.each.test.ts
Labels: change: feat
