Repository web-infra-dev/rstest, pull requests merged in 2025-07, with the labels that each got.

#290 feat: more mock api
  biome.json
  packages/core/src/core/plugins/entry.ts
  packages/core/src/core/plugins/mockRuntime.ts
  packages/core/src/core/rsbuild.ts
  packages/core/src/runtime/api/index.ts
  packages/core/src/runtime/api/utilities.ts
  packages/core/src/runtime/worker/loadModule.ts
  packages/core/src/types/mock.ts
  packages/core/tests/core/__snapshots__/rsbuild.test.ts.snap
  pnpm-lock.yaml
  tests/__mocks__/axios.ts
  tests/__mocks__/fs.js
  tests/__mocks__/redux.ts
  tests/mock/fixtures/unmock/noUnmock.test.ts
  tests/mock/fixtures/unmock/rstest.config.ts
  tests/mock/fixtures/unmock/rstest.setup.ts
  tests/mock/fixtures/unmock/unmock.test.ts
  tests/mock/src/increment.ts
  tests/mock/src/mockedDependency.ts
  tests/mock/src/readSomeFile.ts
  tests/mock/tests/doMock.test.ts
  tests/mock/tests/doMockRequire.test.ts
  tests/mock/tests/doUnmock.test.ts
  tests/mock/tests/external.test.ts
  tests/mock/tests/importActual.test.ts
  tests/mock/tests/index.test.ts
  tests/mock/tests/loadMock.test.ts
  tests/mock/tests/mock.test.ts
  tests/mock/tests/mockNodeProtocol.test.ts
  tests/mock/tests/mockNonResolved.test.ts
  tests/mock/tests/mockRequire.test.ts
  tests/mock/tests/reduxMocked.test.ts
  tests/mock/tests/requireActual.test.ts
  tests/mock/tests/resetModules.test.ts
  tests/mock/tests/unmock.test.ts
  tests/package.json
  tests/scripts/index.ts
  tests/test-api/edgeCase.test.ts
  tests/tsconfig.json
Labels: change: feat

#343 fix: should run tests correctly when isolate false
  packages/core/src/core/plugins/moduleCacheControl.ts
  packages/core/src/core/rsbuild.ts
  packages/core/src/pool/index.ts
  packages/core/src/runtime/worker/index.ts
  packages/core/src/runtime/worker/loadModule.ts
  packages/core/src/types/worker.ts
  packages/core/tests/core/__snapshots__/rsbuild.test.ts.snap
  packages/core/tests/core/rsbuild.test.ts
  tests/singleton/fixtures/index1.test.ts
  tests/singleton/fixtures/rstest.config.ts
  tests/singleton/fixtures/setup.ts
  tests/singleton/index.test.ts
Labels: change: fix

#345 docs: add more configuration items
  website/docs/en/config/test/_meta.json
  website/docs/en/config/test/disableConsoleIntercept.mdx
  website/docs/en/config/test/isolate.mdx
  website/docs/en/config/test/name.mdx
  website/docs/en/config/test/onConsoleLog.mdx
  website/docs/en/config/test/pool.mdx
  website/docs/en/config/test/printConsoleTrace.mdx
  website/docs/en/config/test/update.mdx
  website/docs/zh/config/test/_meta.json
  website/docs/zh/config/test/disableConsoleIntercept.mdx
  website/docs/zh/config/test/isolate.mdx
  website/docs/zh/config/test/name.mdx
  website/docs/zh/config/test/onConsoleLog.mdx
  website/docs/zh/config/test/pool.mdx
  website/docs/zh/config/test/printConsoleTrace.mdx
  website/docs/zh/config/test/update.mdx
Labels: change: docs

#346 docs: add mock configs and `MockInstance` API
  website/docs/en/api/rstest/_meta.json
  website/docs/en/api/rstest/mockFunctions.mdx
  website/docs/en/api/rstest/mockInstance.mdx
  website/docs/en/config/test/_meta.json
  website/docs/en/config/test/clearMocks.mdx
  website/docs/en/config/test/resetMocks.mdx
  website/docs/en/config/test/restoreMocks.mdx
  website/docs/zh/api/rstest/_meta.json
  website/docs/zh/api/rstest/mockFunctions.mdx
  website/docs/zh/api/rstest/mockInstance.mdx
  website/docs/zh/config/test/_meta.json
  website/docs/zh/config/test/clearMocks.mdx
  website/docs/zh/config/test/resetMocks.mdx
  website/docs/zh/config/test/restoreMocks.mdx
Labels: change: docs

#348 docs: add some rstest utilities API
  scripts/dictionary.txt
  website/docs/en/api/rstest/_meta.json
  website/docs/en/api/rstest/mockFunctions.mdx
  website/docs/en/api/rstest/utilities.mdx
  website/docs/en/api/test-api/_meta.json
  website/docs/en/config/test/_meta.json
  website/docs/en/config/test/unstubEnvs.mdx
  website/docs/en/config/test/unstubGlobals.mdx
  website/docs/zh/api/rstest/_meta.json
  website/docs/zh/api/rstest/mockFunctions.mdx
  website/docs/zh/api/rstest/utilities.mdx
  website/docs/zh/api/test-api/_meta.json
  website/docs/zh/config/test/_meta.json
  website/docs/zh/config/test/unstubEnvs.mdx
  website/docs/zh/config/test/unstubGlobals.mdx
Labels: change: docs

#349 fix(mock): resetModules should not clear mock
  packages/core/src/core/plugins/mockRuntime.ts
  pnpm-lock.yaml
  tests/mock/tests/defaultInterop.test.ts
  tests/mock/tests/resetModules.test.ts
  tests/package.json
  tests/rstest.config.ts
Labels: change: fix

#350 docs: add more test configs
  README.md
  website/docs/en/config/test/_meta.json
  website/docs/en/config/test/maxConcurrency.mdx
  website/docs/en/config/test/slowTestThreshold.mdx
  website/docs/en/config/test/testNamePattern.mdx
  website/docs/en/config/test/testTimeout.mdx
  website/docs/zh/config/test/_meta.json
  website/docs/zh/config/test/maxConcurrency.mdx
  website/docs/zh/config/test/slowTestThreshold.mdx
  website/docs/zh/config/test/testNamePattern.mdx
  website/docs/zh/config/test/testTimeout.mdx
Labels: change: docs

#353 release: 0.0.5
  packages/core/package.json
Labels: release

#354 feat: support happy dom test
  packages/core/package.json
  packages/core/src/runtime/worker/env/happyDom.ts
  packages/core/src/runtime/worker/env/jsdom.ts
  packages/core/src/runtime/worker/env/jsdomKeys.ts
  packages/core/src/runtime/worker/env/utils.ts
  packages/core/src/runtime/worker/index.ts
  packages/core/src/types/config.ts
  packages/core/src/types/environment.ts
  pnpm-lock.yaml
  tests/dom/css.test.ts
  tests/dom/fixtures/package.json
  tests/dom/fixtures/rsbuild.config.ts
  tests/dom/fixtures/rstest.config.ts
  tests/dom/fixtures/rstest.externals.config.ts
  tests/dom/fixtures/src/App.css
  tests/dom/fixtures/src/App.module.css
  tests/dom/fixtures/src/App.tsx
  tests/dom/fixtures/src/env.d.ts
  tests/dom/fixtures/src/index.tsx
  tests/dom/fixtures/test/App.test.tsx
  tests/dom/fixtures/test/css.test.tsx
  tests/dom/fixtures/test/handledError.test.tsx
  tests/dom/fixtures/test/jestDom.test.tsx
  tests/dom/fixtures/test/setup.ts
  tests/dom/fixtures/test/test.d.ts
  tests/dom/fixtures/test/unhandledError.test.tsx
  tests/dom/fixtures/tsconfig.json
  tests/dom/handledError.test.ts
  tests/dom/index.test.ts
  tests/dom/unhandledError.test.ts
  tests/jsdom/css.test.ts
  tests/jsdom/handledError.test.ts
  tests/jsdom/index.test.ts
  tests/jsdom/unhandledError.test.ts
  website/docs/en/config/test/testEnvironment.mdx
  website/docs/zh/config/test/testEnvironment.mdx
Labels: change: feat

#363 feat: support hookTimeout
  packages/core/src/cli/commands.ts
  packages/core/src/config.ts
  packages/core/src/pool/index.ts
  packages/core/src/runtime/runner/index.ts
  packages/core/src/runtime/runner/runtime.ts
  packages/core/src/types/config.ts
  packages/core/src/types/worker.ts
  website/docs/en/config/test/_meta.json
  website/docs/en/config/test/hookTimeout.mdx
  website/docs/en/guide/basic/cli.mdx
  website/docs/zh/config/test/_meta.json
  website/docs/zh/config/test/hookTimeout.mdx
  website/docs/zh/guide/basic/cli.mdx
Labels: change: feat

#364 perf: disable some of rsbuild's default devMiddlewares
  packages/core/src/core/rsbuild.ts
Labels: change: perf

#370 docs: add expect API
  website/docs/en/api/rstest/mockFunctions.mdx
  website/docs/en/api/test-api/_meta.json
  website/docs/en/api/test-api/expect.mdx
  website/docs/zh/api/rstest/mockFunctions.mdx
  website/docs/zh/api/test-api/_meta.json
  website/docs/zh/api/test-api/expect.mdx
Labels: change: docs

#374 fix: unexpected resolution of vue to `vue.cjs.prod.js` when `NODE_ENV=test`
  package.json
  packages/core/src/core/rsbuild.ts
  packages/core/tests/core/__snapshots__/rsbuild.test.ts.snap
  pnpm-lock.yaml
  tests/tsconfig.json
  tests/vue/fixtures/package.json
  tests/vue/fixtures/rsbuild.config.ts
  tests/vue/fixtures/rstest.config.ts
  tests/vue/fixtures/src/App.tsx
  tests/vue/fixtures/src/App.vue
  tests/vue/fixtures/src/index.css
  tests/vue/fixtures/src/index.js
  tests/vue/fixtures/test/index.test.ts
  tests/vue/fixtures/test/jsx.test.ts
  tests/vue/fixtures/tsconfig.json
  tests/vue/index.test.ts
Labels: change: fix

#380 release: 0.0.7
  packages/core/package.json
Labels: release

#384 feat: support `--include` CLI option to match test files
  packages/core/src/cli/commands.ts
  website/docs/en/config/test/include.mdx
  website/docs/en/guide/basic/_meta.json
  website/docs/en/guide/basic/test-filter.mdx
  website/docs/zh/config/test/include.mdx
  website/docs/zh/guide/basic/_meta.json
  website/docs/zh/guide/basic/test-filter.mdx
Labels: change: feat

#390 fix: should exit correctly when signal listener exists
  packages/core/src/runtime/worker/index.ts
  tests/runner/test/fixtures/signalListener.test.ts
  tests/runner/test/processKill.test.ts
  tests/runner/test/signalListener.test.ts
Labels: change: fix

#394 feat: support bundle `node_modules` in node environment
  packages/core/src/core/rsbuild.ts
  pnpm-lock.yaml
  tests/externals/bundle.test.ts
  tests/externals/fixtures/bundle.test.ts
  tests/externals/fixtures/rstest.bundle.config.ts
  tests/externals/fixtures/test-bundle/index.ts
  tests/externals/fixtures/test-bundle/package.json
  tests/externals/fixtures/test-pkg/env.d.ts
  tests/externals/fixtures/test-pkg/testBundle.ts
  tests/vue/sfc.test.ts
  website/docs/en/config/build/output.mdx
  website/docs/zh/config/build/output.mdx
Labels: change: feat

#397 docs(api): mock modules
  packages/core/src/types/mock.ts
  website/docs/en/api/rstest/_meta.json
  website/docs/en/api/rstest/mockModules.mdx
  website/docs/zh/api/rstest/_meta.json
  website/docs/zh/api/rstest/mockModules.mdx
Labels: change: docs

#403 release: 0.0.9
  packages/core/package.json
Labels: release

#405 feat: add `RSTEST` flag
  packages/core/src/cli/prepare.ts
  tests/basic/test/index.test.ts
  tests/cli/fixtures/flag.config.ts
  tests/cli/index.test.ts
  website/docs/en/config/test/includeSource.mdx
  website/docs/en/guide/basic/configure-rstest.mdx
  website/docs/zh/config/test/includeSource.mdx
  website/docs/zh/guide/basic/configure-rstest.mdx
Labels: change: feat

#426 docs: add cli options example
  website/docs/en/config/test/clearMocks.mdx
  website/docs/en/config/test/disableConsoleIntercept.mdx
  website/docs/en/config/test/exclude.mdx
  website/docs/en/config/test/globals.mdx
  website/docs/en/config/test/hookTimeout.mdx
  website/docs/en/config/test/include.mdx
  website/docs/en/config/test/isolate.mdx
  website/docs/en/config/test/maxConcurrency.mdx
  website/docs/en/config/test/passWithNoTests.mdx
  website/docs/en/config/test/printConsoleTrace.mdx
  website/docs/en/config/test/resetMocks.mdx
  website/docs/en/config/test/restoreMocks.mdx
  website/docs/en/config/test/retry.mdx
  website/docs/en/config/test/slowTestThreshold.mdx
  website/docs/en/config/test/testEnvironment.mdx
  website/docs/en/config/test/testNamePattern.mdx
  website/docs/en/config/test/testTimeout.mdx
  website/docs/en/config/test/unstubEnvs.mdx
  website/docs/en/config/test/unstubGlobals.mdx
  website/docs/en/config/test/update.mdx
  website/docs/zh/config/test/clearMocks.mdx
  website/docs/zh/config/test/disableConsoleIntercept.mdx
  website/docs/zh/config/test/exclude.mdx
  website/docs/zh/config/test/globals.mdx
  website/docs/zh/config/test/hookTimeout.mdx
  website/docs/zh/config/test/include.mdx
  website/docs/zh/config/test/isolate.mdx
  website/docs/zh/config/test/maxConcurrency.mdx
  website/docs/zh/config/test/passWithNoTests.mdx
  website/docs/zh/config/test/printConsoleTrace.mdx
  website/docs/zh/config/test/resetMocks.mdx
  website/docs/zh/config/test/restoreMocks.mdx
  website/docs/zh/config/test/retry.mdx
  website/docs/zh/config/test/slowTestThreshold.mdx
  website/docs/zh/config/test/testEnvironment.mdx
  website/docs/zh/config/test/testNamePattern.mdx
  website/docs/zh/config/test/testTimeout.mdx
  website/docs/zh/config/test/unstubEnvs.mdx
  website/docs/zh/config/test/unstubGlobals.mdx
  website/docs/zh/config/test/update.mdx
Labels: change: docs

#427 fix: should show `module not found` error codeFrame correctly
  packages/core/src/utils/error.ts
  tests/scripts/index.ts
  tests/test-api/edgeCase.test.ts
  tests/test-api/fixtures/moduleNotFound.codeFrame.test.ts
Labels: change: fix

#428 fix: improve error handling for unhandledRejection exception
  packages/core/src/runtime/worker/index.ts
  tests/dom/fixtures/test/uncaughtException.test.ts
  tests/dom/uncaughtException.test.ts
  tests/scripts/index.ts
Labels: change: fix
