Repository web-infra-dev/rstest, pull requests merged in 2025-09, with the labels that each got.

#528 feat: add JUnit reporter
  e2e/reporter/fixtures/junit.test.ts
  e2e/reporter/junit.test.ts
  packages/core/LICENSE.md
  packages/core/package.json
  packages/core/src/core/rstest.ts
  packages/core/src/reporter/junit.ts
  packages/core/src/utils/error.ts
  packages/core/tests/reporter/junit.test.ts
  pnpm-lock.yaml
  scripts/dictionary.txt
  website/docs/en/config/test/reporters.mdx
  website/docs/zh/config/test/reporters.mdx
Labels: change: feat

#530 docs: add `debugging in VS Code`
  website/docs/en/guide/advanced/_meta.json
  website/docs/en/guide/advanced/debugging.mdx
  website/docs/zh/guide/advanced/_meta.json
  website/docs/zh/guide/advanced/debugging.mdx
Labels: change: docs

#538 release: 0.3.2
  packages/core/package.json
Labels: release

#540 fix: resolve project's tsconfig path correctly
  e2e/projects/fixtures/packages/node/test/index.test.ts
  e2e/projects/fixtures/packages/node/tsconfig.json
  e2e/tsconfig.json
  packages/core/src/core/plugins/basic.ts
  packages/core/src/core/rsbuild.ts
  packages/core/src/core/rstest.ts
  packages/core/src/utils/constants.ts
  packages/core/tests/core/__snapshots__/rsbuild.test.ts.snap
  packages/core/tests/core/rsbuild.test.ts
Labels: change: fix

#534 docs: add features chapter
  website/docs/en/guide/start/_meta.json
  website/docs/en/guide/start/features.mdx
  website/docs/zh/guide/start/_meta.json
  website/docs/zh/guide/start/features.mdx
Labels: change: docs

#541 docs: use Algolia search
  pnpm-lock.yaml
  website/package.json
  website/rspress.config.ts
  website/theme/index.tsx
Labels: change: docs

#551 fix: add `rs` to global API
  packages/core/globals.d.ts
Labels: change: fix

#553 release: 0.3.3
  packages/core/package.json
Labels: release

#554 fix: support use rstest global APIs in external modules
  e2e/runner/test/fixtures/globals.test.ts
  e2e/runner/test/fixtures/test-rstest-globals/index.js
  e2e/runner/test/fixtures/test-rstest-globals/package.json
  e2e/runner/test/runner.test.ts
  packages/core/src/runtime/worker/index.ts
  pnpm-lock.yaml
Labels: change: fix

#562 fix(coverage): fix coverage exclusion on windows
  e2e/projects/coverage.test.ts
  e2e/test-coverage/index.test.ts
  packages/coverage-istanbul/package.json
  pnpm-lock.yaml
Labels: change: fix

#560 feat: support check coverage thresholds
  e2e/scripts/index.ts
  e2e/test-coverage/fixtures/rstest.thresholds.config.ts
  e2e/test-coverage/index.test.ts
  packages/core/src/core/runTests.ts
  packages/core/src/coverage/checkThresholds.ts
  packages/core/src/types/coverage.ts
Labels: change: feat

#564 docs: add `coverage` configuration
  website/docs/en/config/test/_meta.json
  website/docs/en/config/test/coverage.mdx
  website/docs/zh/config/test/_meta.json
  website/docs/zh/config/test/coverage.mdx
  website/theme/components/ConfigOverview.tsx
Labels: change: docs

#569 docs: polish coverage doc
  website/docs/en/config/test/coverage.mdx
  website/docs/en/guide/start/features.mdx
  website/docs/zh/config/test/coverage.mdx
  website/docs/zh/guide/start/features.mdx
Labels: change: docs

#570 feat: allow set coverage thresholds as negative number
  e2e/test-coverage/fixtures/rstest.thresholds.config.ts
  e2e/test-coverage/fixtures/test/string.test.ts
  e2e/test-coverage/index.test.ts
  packages/core/src/coverage/checkThresholds.ts
  packages/core/src/types/coverage.ts
  website/docs/en/config/test/coverage.mdx
  website/docs/zh/config/test/coverage.mdx
Labels: change: feat

#572 docs: update `@rstest/coverage-istanbul` readme
  packages/coverage-istanbul/README.md
  packages/coverage-istanbul/package.json
Labels: change: docs

#579 docs: update jest configuration mappings
  website/docs/en/guide/migration/jest.mdx
  website/docs/zh/guide/migration/jest.mdx
Labels: change: docs

#580 release: 0.4.1
  packages/core/package.json
  packages/coverage-istanbul/package.json
Labels: release

#590 feat: support check coverage threshold for per file
  e2e/test-coverage/fixtures/rstest.perFileThresholds.config.ts
  e2e/test-coverage/thresholds.test.ts
  packages/core/src/coverage/checkThresholds.ts
  packages/core/src/coverage/generate.ts
  packages/core/src/runtime/worker/index.ts
  packages/core/src/types/coverage.ts
  website/docs/en/config/test/coverage.mdx
  website/docs/zh/config/test/coverage.mdx
Labels: change: feat

#588 feat!: merge `exclude` values by default
  e2e/exclude/fixtures/index.test.ts
  e2e/exclude/fixtures/rstest.override.config.ts
  e2e/exclude/index.test.ts
  packages/core/src/config.ts
  packages/core/src/core/listTests.ts
  packages/core/src/core/runTests.ts
  packages/core/src/types/config.ts
  packages/core/tests/__snapshots__/config.test.ts.snap
  packages/core/tests/config.test.ts
  packages/core/tests/core/__snapshots__/rstest.test.ts.snap
  website/docs/en/config/test/exclude.mdx
  website/docs/zh/config/test/exclude.mdx
Labels: change: feat

#591 docs: update `coverage.include`
  website/docs/en/config/test/coverage.mdx
  website/docs/zh/config/test/coverage.mdx
Labels: change: docs

#595 release: 0.5.0
  packages/core/package.json
  packages/coverage-istanbul/package.json
Labels: release

#603 docs: update jest api alternative
  website/docs/en/guide/migration/jest.mdx
  website/docs/zh/guide/migration/jest.mdx
Labels: change: docs

#607 docs: introduce beforeEach / beforeAll returns
  website/docs/en/api/test-api/hooks.mdx
  website/docs/en/guide/migration/jest.mdx
  website/docs/zh/api/test-api/hooks.mdx
  website/docs/zh/guide/migration/jest.mdx
Labels: change: docs

#609 feat: support `snapshotFormat` option
  e2e/snapshot/fixtures/__snapshots__/options.test.ts.snap
  e2e/snapshot/fixtures/options.test.ts
  e2e/snapshot/fixtures/rstest.options.config.ts
  e2e/snapshot/options.test.ts
  packages/core/src/config.ts
  packages/core/src/pool/index.ts
  packages/core/src/runtime/worker/index.ts
  packages/core/src/types/config.ts
  packages/core/src/types/worker.ts
  packages/core/tests/__snapshots__/config.test.ts.snap
  packages/core/tests/core/__snapshots__/rstest.test.ts.snap
  website/docs/en/config/test/_meta.json
  website/docs/en/config/test/snapshotFormat.mdx
  website/docs/zh/config/test/_meta.json
  website/docs/zh/config/test/snapshotFormat.mdx
  website/theme/components/ConfigOverview.tsx
Labels: change: feat

#610 release: 0.5.1
  packages/core/package.json
Labels: release
