Repository web-infra-dev/rstest, pull requests merged in 2025-05, with the labels that each got.

#162 feat: init mock API type declaration
  packages/core/src/runtime/api/utilities.ts
  packages/core/src/types/mock.ts
  pnpm-lock.yaml
  tests/mock/package.json
  tests/mock/tests/external.test.ts
Labels: change: feat

#154 feat: support apply some build configs
  packages/core/src/core/rsbuild.ts
  packages/core/src/core/runTests.ts
  packages/core/src/pool/index.ts
  packages/core/src/runtime/runner/index.ts
  packages/core/src/runtime/runner/runner.ts
  packages/core/src/runtime/worker/index.ts
  packages/core/src/types/config.ts
  packages/core/src/types/worker.ts
  tests/build/fixtures/alias/index.test.ts
  tests/build/fixtures/alias/rstest.config.ts
  tests/build/fixtures/alias/src/a.ts
  tests/build/fixtures/alias/src/b.ts
  tests/build/fixtures/alias/src/index.ts
  tests/build/fixtures/define/env.d.ts
  tests/build/fixtures/define/index.test.ts
  tests/build/fixtures/define/rstest.config.ts
  tests/build/fixtures/plugin/index.test.ts
  tests/build/fixtures/plugin/rstest.config.ts
  tests/build/fixtures/plugin/src/a.ts
  tests/build/fixtures/plugin/src/index.ts
  tests/build/index.test.ts
Labels: change: feat

#163 feat: support `output.cssModules` configuration
  packages/core/src/core/rsbuild.ts
  packages/core/src/pool/index.ts
  packages/core/src/types/config.ts
  packages/core/src/types/worker.ts
  tests/build/fixtures/cssModules/index.test.ts
  tests/build/fixtures/cssModules/rstest.config.ts
  tests/build/fixtures/cssModules/src/env.d.ts
  tests/build/fixtures/cssModules/src/index.module.css
  tests/build/fixtures/cssModules/src/index.ts
Labels: change: feat

#165 feat: support tools rspack / swc / bundlerChain configs
  packages/core/src/core/rsbuild.ts
  packages/core/src/pool/index.ts
  packages/core/src/types/config.ts
  packages/core/src/types/worker.ts
  packages/core/src/utils/helper.ts
  tests/build/fixtures/tools/rspack/index.test.ts
  tests/build/fixtures/tools/rspack/rstest.config.ts
  tests/build/fixtures/tools/rspack/src/a.ts
  tests/build/fixtures/tools/rspack/src/b.ts
  tests/build/fixtures/tools/rspack/src/index.ts
  tests/build/index.test.ts
Labels: change: feat

#169 feat: support run tests in parallel
  packages/core/src/reporter/summary.ts
  packages/core/src/runtime/runner/runner.ts
  packages/core/src/runtime/runner/runtime.ts
  packages/core/src/runtime/runner/task.ts
  packages/core/src/types/api.ts
  packages/core/src/types/testSuite.ts
  tests/test-api/concurrent.test.ts
  tests/test-api/fixtures/concurrent.test.ts
  tests/test-api/fixtures/concurrentIsolated.test.ts
  tests/test-api/fixtures/concurrentLimit.test.ts
  tests/test-api/fixtures/concurrentNested.test.ts
Labels: change: feat

#170 feat: support `describe.concurrent`
  packages/core/src/runtime/runner/runtime.ts
  packages/core/src/types/api.ts
  tests/describe/concurrent.test.ts
  tests/describe/fixtures/concurrent.test.ts
Labels: change: feat

#171 feat: support maxConcurrency option
  packages/core/src/cli/commands.ts
  packages/core/src/config.ts
  packages/core/src/pool/index.ts
  packages/core/src/runtime/runner/runner.ts
  packages/core/src/types/config.ts
  packages/core/src/types/worker.ts
  tests/test-api/concurrent.test.ts
Labels: change: feat

#173 feat: support get expect from test context
  packages/core/src/runtime/runner/runner.ts
  packages/core/src/runtime/runner/runtime.ts
  packages/core/src/types/api.ts
  packages/core/src/types/testSuite.ts
  tests/test-api/__snapshots__/concurrentContext.test.ts.snap
  tests/test-api/concurrentContext.test.ts
Labels: change: feat

#176 feat: support console source stack trace
  packages/core/package.json
  packages/core/src/runtime/worker/index.ts
  packages/core/src/runtime/worker/snapshot.ts
  pnpm-lock.yaml
  tests/log/fixtures/trace.test.ts
  tests/log/index.test.ts
  tests/setup/index.test.ts
Labels: change: feat

#178 feat: support print console traces when calling console method
  packages/core/src/cli/commands.ts
  packages/core/src/config.ts
  packages/core/src/pool/index.ts
  packages/core/src/reporter/index.ts
  packages/core/src/runtime/worker/console.ts
  packages/core/src/runtime/worker/index.ts
  packages/core/src/types/config.ts
  packages/core/src/types/testSuite.ts
  packages/core/src/types/worker.ts
  tests/log/index.test.ts
Labels: change: feat

#179 feat: support proxy more console methods
  packages/core/src/reporter/index.ts
  packages/core/src/runtime/worker/console.ts
  packages/core/src/types/testSuite.ts
  tests/log/fixtures/log.test.ts
  tests/log/index.test.ts
Labels: change: feat

#180 feat: support disableConsoleIntercept
  packages/core/src/cli/commands.ts
  packages/core/src/config.ts
  packages/core/src/pool/index.ts
  packages/core/src/runtime/worker/index.ts
  packages/core/src/types/config.ts
  packages/core/src/types/worker.ts
  tests/log/index.test.ts
Labels: change: feat

#181 feat: make all test API chainable
  packages/core/src/runtime/runner/runtime.ts
  packages/core/src/types/api.ts
  tests/describe/chain.test.ts
  tests/test-api/chain.test.ts
Labels: change: feat

#184 feat: support `test.sequential`
  packages/core/src/runtime/runner/runtime.ts
  packages/core/src/types/api.ts
  packages/core/src/types/testSuite.ts
  tests/describe/chain.test.ts
  tests/describe/fixtures/sequential.test.ts
  tests/describe/sequential.test.ts
  tests/test-api/chain.test.ts
  tests/test-api/fixtures/sequential.test.ts
  tests/test-api/sequential.test.ts
Labels: change: feat

#185 feat: init rstest list command
  packages/core/src/cli/commands.ts
  packages/core/src/cli/prepare.ts
  packages/core/src/core/runTests.ts
  packages/core/src/pool/index.ts
  packages/core/src/types/core.ts
  tests/list/fixtures/a.test.ts
  tests/list/fixtures/b.test.ts
  tests/list/index.test.ts
Labels: change: feat

#186 feat: support collect & list tests
  packages/core/src/cli/commands.ts
  packages/core/src/core/index.ts
  packages/core/src/core/listTests.ts
  packages/core/src/core/runTests.ts
  packages/core/src/pool/forks.ts
  packages/core/src/pool/index.ts
  packages/core/src/runtime/api/index.ts
  packages/core/src/runtime/runner/index.ts
  packages/core/src/runtime/runner/runner.ts
  packages/core/src/runtime/worker/index.ts
  packages/core/src/types/core.ts
  packages/core/src/types/worker.ts
  tests/list/index.test.ts
  tests/scripts/index.ts
Labels: change: feat

#187 fix: should list tests correctly with test name filter
  packages/core/src/core/listTests.ts
  tests/list/index.test.ts
Labels: change: fix

#191 feat: support only list the test files
  packages/core/src/cli/commands.ts
  packages/core/src/core/index.ts
  packages/core/src/core/listTests.ts
  packages/core/src/pool/forks.ts
  packages/core/src/pool/index.ts
  packages/core/src/runtime/worker/index.ts
  packages/core/src/types/core.ts
  tests/list/index.test.ts
Labels: change: feat

#192 feat: support print tests as JSON
  packages/core/src/cli/commands.ts
  packages/core/src/core/listTests.ts
  packages/core/src/types/core.ts
  tests/list/index.test.ts
  tests/rstest.config.ts
  tests/rstest.setup.ts
Labels: change: feat

#193 feat(list): support output test json to file
  packages/core/src/cli/commands.ts
  packages/core/src/core/listTests.ts
  packages/core/src/types/core.ts
  tests/list/index.test.ts
Labels: change: feat

#195 feat: support slowTestThreshold option
  packages/core/src/cli/commands.ts
  packages/core/src/config.ts
  packages/core/src/reporter/index.ts
  packages/core/src/types/config.ts
  tests/rstest.config.ts
Labels: change: feat

#196 feat(reporter): support render status
  packages/core/src/core/context.ts
  packages/core/src/reporter/index.ts
  packages/core/src/reporter/statusRenderer.ts
  packages/core/src/reporter/windowedRenderer.ts
Labels: change: feat

#198 fix: should print console trace correctly
  packages/core/src/reporter/index.ts
  tests/log/fixtures/logSrc.test.ts
  tests/log/fixtures/src/index.ts
  tests/log/index.test.ts
  tests/log/trace.test.ts
Labels: change: fix

#199 fix: should not mark snapshot obsolete when case skipped
  packages/core/src/runtime/runner/runner.ts
  tests/snapshot/fixtures/__snapshots__/obsolete.test.ts.snap
  tests/snapshot/fixtures/__snapshots__/skip.test.ts.snap
  tests/snapshot/fixtures/obsolete.test.ts
  tests/snapshot/fixtures/skip.test.ts
  tests/snapshot/obsolete.test.ts
Labels: change: fix

#201 feat: in-source testing
  packages/core/importMeta.d.ts
  packages/core/package.json
  packages/core/src/config.ts
  packages/core/src/core/listTests.ts
  packages/core/src/core/rsbuild.ts
  packages/core/src/core/runTests.ts
  packages/core/src/types/config.ts
  packages/core/src/utils/testFiles.ts
  packages/core/tests/core/__snapshots__/rsbuild.test.ts.snap
  pnpm-lock.yaml
  tests/in-source/fixtures/rslib.config.ts
  tests/in-source/fixtures/rstest.config.ts
  tests/in-source/fixtures/src/a.ts
  tests/in-source/fixtures/src/index.ts
  tests/in-source/fixtures/tsconfig.json
  tests/in-source/index.test.ts
  tests/package.json
Labels: change: feat

#202 docs: initialize Rstest website
  pnpm-lock.yaml
  website/.gitignore
  website/LICENSE
  website/README.md
  website/docs/en/_meta.json
  website/docs/en/index.md
  website/docs/zh/_meta.json
  website/docs/zh/index.md
  website/env.d.ts
  website/i18n.json
  website/package.json
  website/rspress.config.ts
  website/theme/components/Copyright.module.scss
  website/theme/components/Copyright.tsx
  website/theme/components/Hero.module.scss
  website/theme/components/Hero.tsx
  website/theme/components/ImageAlt.tsx
  website/theme/components/NextSteps.module.scss
  website/theme/components/NextSteps.tsx
  website/theme/components/Overview.module.scss
  website/theme/components/Overview.tsx
  website/theme/components/RsbuildDocBadge.tsx
  website/theme/components/Step.module.scss
  website/theme/components/Step.tsx
  website/theme/components/ToolStack.tsx
  website/theme/components/utils.ts
  website/theme/env.d.ts
  website/theme/index.scss
  website/theme/index.tsx
  website/theme/pages/index.tsx
  website/tsconfig.json
Labels: change: docs

#204 feat: init `test.extend` API
  packages/core/src/runtime/runner/runner.ts
  packages/core/src/runtime/runner/runtime.ts
  packages/core/src/types/api.ts
  packages/core/src/types/testSuite.ts
  tests/test-api/chain.test.ts
  tests/test-api/extend.test.ts
Labels: change: feat

#206 fix: reverse execution of extend cleanup function
  packages/core/src/runtime/runner/runner.ts
  tests/test-api/extend.depends.test.ts
  tests/test-api/extend.extend.test.ts
  tests/test-api/extend.test.ts
Labels: change: fix

#212 fix(extend): support define an option
  packages/core/src/runtime/runner/runner.ts
  tests/test-api/extend.test.ts
Labels: change: fix

#211 docs: add 'setup environment' chapter
  packages/core/package.json
  website/docs/en/guide/_meta.json
  website/docs/en/guide/start/quick-start.mdx
  website/docs/zh/guide/_meta.json
  website/docs/zh/guide/start/quick-start.mdx
Labels: change: docs

#215 feat: support fixtures on-demand & `auto` option
  packages/core/src/reporter/summary.ts
  packages/core/src/runtime/runner/fixtures.ts
  packages/core/src/runtime/runner/runner.ts
  packages/core/src/runtime/runner/runtime.ts
  packages/core/src/types/api.ts
  packages/core/src/types/testSuite.ts
  packages/core/src/utils/helper.ts
  tests/test-api/extend.auto.test.ts
  tests/test-api/extend.extend.test.ts
  tests/test-api/extend.onDemand.test.ts
Labels: change: feat

#216 docs: add `Introduction` chapter
  website/docs/en/_meta.json
  website/docs/en/guide/_meta.json
  website/docs/en/guide/start/_meta.json
  website/docs/en/guide/start/index.mdx
  website/docs/zh/_meta.json
  website/docs/zh/guide/_meta.json
  website/docs/zh/guide/start/_meta.json
  website/docs/zh/guide/start/index.mdx
Labels: change: docs

#218 docs: use Open Sans as the default font
  pnpm-lock.yaml
  website/package.json
  website/rspress.config.ts
Labels: change: docs

#225 fix: file not found error when printCodeFrame
  packages/core/src/reporter/summary.ts
Labels: change: fix

#230 fix(types): missing type in preview version
  .github/workflows/preview.yml
  packages/core/package.json
  packages/core/rslib.config.ts
  packages/core/src/core/listTests.ts
  packages/core/src/node.ts
  pnpm-lock.yaml
Labels: change: fix

#231 fix: should keep dynamic import expressions
  packages/core/src/core/rsbuild.ts
  packages/core/tests/core/__snapshots__/rsbuild.test.ts.snap
  tests/build/runtimeImport/a.js
  tests/build/runtimeImport/b.ts
  tests/build/runtimeImport/index.test.ts
  tests/build/runtimeImport/package.json
Labels: change: fix

#232 docs: redirect rstest.dev to rstest.rs
  website/docs/public/_redirects
Labels: change: docs

#238 fix: `--cpu-prof` not working in child_process
  packages/core/src/runtime/worker/index.ts
  packages/core/src/runtime/worker/setup.ts
Labels: change: fix

#241 docs: add `Rsdoctor` guide
  website/docs/en/guide/_meta.json
  website/docs/en/guide/advanced/_meta.json
  website/docs/en/guide/advanced/profiling.mdx
  website/docs/zh/guide/_meta.json
  website/docs/zh/guide/advanced/_meta.json
  website/docs/zh/guide/advanced/profiling.mdx
Labels: change: docs

#242 feat: support `--perf-prof` option in worker
  packages/core/src/pool/index.ts
  packages/core/src/runtime/worker/setup.ts
Labels: change: feat
