Repository web-infra-dev/rstest, pull requests merged in 2025-08, with the labels that each got.

#429 feat: support Github Actions Reporter
  packages/core/src/config.ts
  packages/core/src/core/context.ts
  packages/core/src/reporter/githubActions.ts
  packages/core/src/utils/error.ts
  tests/reporter/fixtures/githubActions.test.ts
  tests/reporter/githubActions.test.ts
  tests/reporter/index.test.ts
  website/docs/en/config/test/reporters.mdx
  website/docs/zh/config/test/reporters.mdx
Labels: change: feat

#433 release: 0.1.0
  packages/core/package.json
Labels: release

#436 perf: prebundle runtime dependencies
  packages/core/LICENSE
  packages/core/package.json
  packages/core/rslib.config.ts
  pnpm-lock.yaml
  scripts/dictionary.txt
Labels: change: perf

#439 fix: should throw error when unknown environment
  packages/core/src/runtime/worker/index.ts
  tests/dom/handledError.test.ts
  tests/dom/utils.ts
Labels: change: fix

#441 docs: fix `@sinonjs/fake-timers` link
  website/docs/en/api/rstest/fakeTimers.mdx
  website/docs/zh/api/rstest/fakeTimers.mdx
Labels: change: docs

#440 fix: shim `require` in rstest bundle
  packages/core/rslib.config.ts
  packages/core/src/runtime/api/poll.ts
  packages/core/src/runtime/runner/task.ts
  packages/core/src/runtime/util.ts
  packages/core/src/runtime/worker/index.ts
  tests/fakeTimers/index.test.ts
Labels: change: fix

#444 release: 0.1.1
  packages/core/licensePlugin.ts
  packages/core/package.json
Labels: release

#447 docs: add alias for rstest utility API
  website/docs/en/api/rstest/fakeTimers.mdx
  website/docs/en/api/rstest/mockFunctions.mdx
  website/docs/en/api/rstest/utilities.mdx
  website/docs/zh/api/rstest/fakeTimers.mdx
  website/docs/zh/api/rstest/mockFunctions.mdx
  website/docs/zh/api/rstest/utilities.mdx
Labels: change: docs

#446 docs: add note for `describe.skip`
  website/docs/en/api/test-api/describe.mdx
  website/docs/zh/api/test-api/describe.mdx
Labels: change: docs

#445 fix: use `inline-source-map` when debugger
  packages/core/src/core/plugins/inspect.ts
  packages/core/src/core/rsbuild.ts
Labels: change: fix

#449 release: 0.1.2
  packages/core/package.json
Labels: release

#452 docs: remove duplicate Rstack description sections
  README.md
  website/docs/en/guide/start/index.mdx
Labels: change: docs

#455 feat: support update snapshot via `u` shortcut
  packages/core/src/core/cliShortcuts.ts
  packages/core/src/core/listTests.ts
  packages/core/src/core/runTests.ts
  packages/core/src/pool/index.ts
Labels: change: feat

#456 feat: support rerun failed tests via `f` shortcut
  packages/core/src/core/cliShortcuts.ts
  packages/core/src/core/rsbuild.ts
  packages/core/src/core/runTests.ts
Labels: change: feat

#458 docs: add `CLI shortcuts` section
  packages/core/src/core/runTests.ts
  website/docs/en/guide/basic/cli.mdx
  website/docs/zh/guide/basic/cli.mdx
Labels: change: docs

#460 release: 0.1.3
  packages/core/package.json
Labels: release

#462 feat: support filter test name regex pattern via `t` shortcut
  packages/core/src/core/cliShortcuts.ts
  packages/core/src/core/listTests.ts
  packages/core/src/core/runTests.ts
  packages/core/src/pool/index.ts
  website/docs/en/guide/basic/cli.mdx
  website/docs/zh/guide/basic/cli.mdx
Labels: change: feat

#478 feat!: update minimum Node.js version to 18.12.0
  package.json
  packages/core/package.json
Labels: change: feat

#480 fix(perf): default worker counts
  packages/core/src/core/runTests.ts
Labels: change: fix

#481 release: 0.2.1
  packages/core/package.json
Labels: release

#482 feat(cli): add short option -w for watch mode
  packages/core/src/cli/commands.ts
  website/docs/en/guide/basic/cli.mdx
  website/docs/zh/guide/basic/cli.mdx
Labels: change: feat

#493 feat: support `onTestFinished` hook
  e2e/lifecycle/fixtures/onTestFinished.failed.test.ts
  e2e/lifecycle/fixtures/onTestFinished.outside.test.ts
  e2e/lifecycle/fixtures/onTestFinished.test.ts
  e2e/lifecycle/onTestFinished.test.ts
  packages/core/src/runtime/api/public.ts
  packages/core/src/runtime/runner/index.ts
  packages/core/src/runtime/runner/runner.ts
  packages/core/src/runtime/runner/runtime.ts
  packages/core/src/types/api.ts
  website/docs/en/api/test-api/hooks.mdx
  website/docs/zh/api/test-api/hooks.mdx
Labels: change: feat

#500 docs: add chainable modifiers examples
  website/docs/en/api/test-api/describe.mdx
  website/docs/en/api/test-api/test.mdx
Labels: change: docs

#475 feat: re-run on demand in watch mode.
  e2e/watch/index.test.ts
  e2e/watch/shortcuts.test.ts
  packages/core/src/core/context.ts
  packages/core/src/core/index.ts
  packages/core/src/core/plugins/basic.ts
  packages/core/src/core/rsbuild.ts
  packages/core/src/core/rstest.ts
  packages/core/src/core/runTests.ts
  packages/core/src/reporter/githubActions.ts
  packages/core/src/reporter/index.ts
  packages/core/src/reporter/summary.ts
  packages/core/src/runtime/api/poll.ts
  packages/core/src/runtime/runner/runtime.ts
  packages/core/src/types/reporter.ts
  packages/core/src/types/worker.ts
Labels: change: feat

#508 fix: manualMockRoot in projects
  e2e/projects/fixtures/packages/node/__mocks__/fs.js
  e2e/projects/fixtures/packages/node/src/readSomeFile.ts
  e2e/projects/fixtures/packages/node/test/mockFs.test.ts
  packages/core/src/core/plugins/basic.ts
Labels: change: fix

#515 fix: should avoid outputs conflict in projects
  e2e/projects/fixtures/packages/client/test/index.test.ts
  packages/core/src/core/plugins/basic.ts
  packages/core/tests/core/__snapshots__/rsbuild.test.ts.snap
  packages/core/tests/core/rsbuild.test.ts
Labels: change: fix

#516 fix: should not expand diff by default
  e2e/snapshot/diff.test.ts
  e2e/snapshot/fixtures/__snapshots__/diff.test.ts.snap
  e2e/snapshot/fixtures/diff.test.ts
  packages/core/src/runtime/util.ts
Labels: change: fix

#520 feat: support filter projects via `--project` option
  e2e/projects/filter.test.ts
  packages/core/src/cli/commands.ts
  packages/core/src/cli/init.ts
  packages/core/src/utils/testFiles.ts
  packages/core/tests/utils/testFiles.test.ts
  website/docs/en/config/test/name.mdx
  website/docs/en/config/test/projects.mdx
  website/docs/en/guide/basic/cli.mdx
  website/docs/en/guide/basic/test-filter.mdx
  website/docs/zh/config/test/name.mdx
  website/docs/zh/config/test/projects.mdx
  website/docs/zh/guide/basic/cli.mdx
  website/docs/zh/guide/basic/test-filter.mdx
Labels: change: feat

#522 feat: support inline project config
  e2e/projects/fixtures/rstest.inline.config.ts
  e2e/projects/inline.test.ts
  packages/core/src/cli/init.ts
  packages/core/src/core/rstest.ts
  packages/core/src/types/config.ts
  packages/core/src/types/core.ts
  website/docs/en/config/test/projects.mdx
  website/docs/zh/config/test/projects.mdx
Labels: change: feat
